In [2]:
from abc import ABCMeta

from qutip import *
from qutip.qip.operations import *
from qutip.qip.circuit import QubitCircuit, Gate

import numpy as np
from numpy import pi

import scipy as sp
import scipy.integrate as spint
import scipy.linalg as splinalg
import scipy.optimize as spopt

import plotly.express as px

import matplotlib.pyplot as plt

Implemet simple ´qaoa´ solver for general Hamiltonian given as $Z$-polynomial

$$

    H = C + \sum_{i}c_{i}Z_{i} + \sum_{i,j}c_{i,j}Z_{i}Z_{j} + \sum_{i,j,k}c_{i,j,k}Z_{i}Z_{j}Z_{k} + \dots

$$
\\
For that write global functions for all parts of `qaoa` $\rightarrow$ *trial state preperation*, *measurement*, computing the *expectation* .
Write custom, abstract `OPTIMIZER` class wich can be substituted by scipy optimizers like `cobyla` and then later by the `tdvp optimizer`. 

In [27]:
def sz(n:int,i:int):
    return expand_operator(sigmaz(),n,i,[2 for _ in range(n)])

def sx(n:int,i:int):
    return expand_operator(sigmax(),n,i,[2 for _ in range(n)])

In [26]:
sz(3,2)

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]]

In [29]:
H = tensor(sigmaz(),sigmaz(),sigmaz())
B = sum([sx(3,_) for _ in range(3)])

In [30]:
B

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0. 1. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0. 0. 1.]
 [0. 0. 0. 1. 0. 1. 1. 0.]]

In [7]:
def qaoa_circuit(p:int, hamiltonian:Qobj, betas:list[float], gammas:list[float], initial_state:Qobj, mixer:Qobj=None) -> QubitCircuit:
    assert hamiltonian.isherm, "hamiltonian must be hermetian"
    n = np.log2(hamiltonian.dims[0][0])
    if mixer is None:
        mixer = sum([sx(_) for _ in range(n)])

    qc = QubitCircuit(n,initial_state=['+' for _ in range(n)])

    for i in range(p):
        
    # look up QobjEvo for parameter dependency

SyntaxError: invalid syntax (4208766137.py, line 4)

In [8]:
def expectation(circuit, function) -> float:
    pass

In [ ]:
class OPTIMIZER(metaclass=ABCmeta):
    pass